apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bad-role-binding
  namespace: kube-system
subjects:
- kind: User
  name: system:anonymous
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
