apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bad-role-authenticated-binding
  namespace: kube-system
subjects:
- kind: Group
  name: system:authenticated
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
